2017-10-26T08:14:47.134 - [ErrorLogger] - Error when executing MySQL query: 
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown database 'icarus'
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:548)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:540)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
	at org.alexdev.icarus.dao.mysql.Storage.<init>(Storage.java:40)
	at org.alexdev.icarus.dao.mysql.Dao.connect(Dao.java:21)
	at org.alexdev.icarus.Icarus.main(Icarus.java:65)
Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'icarus'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:376)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:448)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:519)
	... 5 more
